# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class BillPaySwitchIdentity(BaseModel):
    """
    Identity information for the user. Mandatory when use case is BPS.
    """ # noqa: E501
    first_name: Annotated[str, Field(strict=True, max_length=50)] = Field(description="User first name", alias="firstName")
    last_name: Annotated[str, Field(strict=True, max_length=50)] = Field(description="User last name", alias="lastName")
    zip_code: Annotated[str, Field(min_length=5, strict=True, max_length=10)] = Field(description="Postal / zip code of the user", alias="zipCode")
    address: Annotated[str, Field(strict=True, max_length=100)] = Field(description="First line of user address")
    address2: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, description="Second line of user address")
    city: Annotated[str, Field(strict=True, max_length=100)] = Field(description="City in which user is located")
    state: Annotated[str, Field(strict=True, max_length=2)] = Field(description="State in which user is located")
    phone: Annotated[str, Field(strict=True, max_length=15)] = Field(description="User phone number")
    email: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, description="User email address")
    __properties: ClassVar[List[str]] = ["firstName", "lastName", "zipCode", "address", "address2", "city", "state", "phone", "email"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BillPaySwitchIdentity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BillPaySwitchIdentity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "firstName": obj.get("firstName"),
            "lastName": obj.get("lastName"),
            "zipCode": obj.get("zipCode"),
            "address": obj.get("address"),
            "address2": obj.get("address2"),
            "city": obj.get("city"),
            "state": obj.get("state"),
            "phone": obj.get("phone"),
            "email": obj.get("email")
        })
        return _obj


