# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.cash_flow_analytics_metrics import CashFlowAnalyticsMetrics
from openapi_client.models.obb_current_report_request_details import ObbCurrentReportRequestDetails
from openapi_client.models.obb_data_availability import ObbDataAvailability
from typing import Optional, Set
from typing_extensions import Self

class CashFlowAnalyticsBusinessSummary(BaseModel):
    """
    Cash flow analytics summarized across all accounts in the report
    """ # noqa: E501
    cashflow_analytics_metrics: Optional[CashFlowAnalyticsMetrics] = Field(default=None, alias="cashflowAnalyticsMetrics")
    current_report_request: ObbCurrentReportRequestDetails = Field(alias="currentReportRequest")
    historic_data_availability: ObbDataAvailability = Field(alias="historicDataAvailability")
    __properties: ClassVar[List[str]] = ["cashflowAnalyticsMetrics", "currentReportRequest", "historicDataAvailability"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CashFlowAnalyticsBusinessSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of cashflow_analytics_metrics
        if self.cashflow_analytics_metrics:
            _dict['cashflowAnalyticsMetrics'] = self.cashflow_analytics_metrics.to_dict()
        # override the default output from pydantic by calling `to_dict()` of current_report_request
        if self.current_report_request:
            _dict['currentReportRequest'] = self.current_report_request.to_dict()
        # override the default output from pydantic by calling `to_dict()` of historic_data_availability
        if self.historic_data_availability:
            _dict['historicDataAvailability'] = self.historic_data_availability.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CashFlowAnalyticsBusinessSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cashflowAnalyticsMetrics": CashFlowAnalyticsMetrics.from_dict(obj["cashflowAnalyticsMetrics"]) if obj.get("cashflowAnalyticsMetrics") is not None else None,
            "currentReportRequest": ObbCurrentReportRequestDetails.from_dict(obj["currentReportRequest"]) if obj.get("currentReportRequest") is not None else None,
            "historicDataAvailability": ObbDataAvailability.from_dict(obj["historicDataAvailability"]) if obj.get("historicDataAvailability") is not None else None
        })
        return _obj


