# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class MonthlyIncome(BaseModel):
    """
    Current estimated monthly pay for the employment.  This is a mandatory field only for VOIE-payroll report type.
    """ # noqa: E501
    estimated_monthly_base_pay: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Mastercard Open Finance estimated monthly base pay amount for the employment", alias="estimatedMonthlyBasePay")
    estimated_monthly_overtime_pay: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Mastercard Open Finance estimated monthly overtime pay amount for the employment", alias="estimatedMonthlyOvertimePay")
    estimated_monthly_bonus_pay: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Mastercard Open Finance estimated monthly bonus pay amount for the employment", alias="estimatedMonthlyBonusPay")
    estimated_monthly_other_pay: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Mastercard Open Finance estimated monthly other pay amount for the employment", alias="estimatedMonthlyOtherPay")
    estimated_monthly_total_pay: Union[StrictFloat, StrictInt] = Field(description="Sum of all Mastercard Open Finance estimated monthly pay amounts", alias="estimatedMonthlyTotalPay")
    estimated_monthly_commission_pay: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Mastercard Open Finance estimated monthly commission pay amount for the employment", alias="estimatedMonthlyCommissionPay")
    __properties: ClassVar[List[str]] = ["estimatedMonthlyBasePay", "estimatedMonthlyOvertimePay", "estimatedMonthlyBonusPay", "estimatedMonthlyOtherPay", "estimatedMonthlyTotalPay", "estimatedMonthlyCommissionPay"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MonthlyIncome from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MonthlyIncome from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "estimatedMonthlyBasePay": obj.get("estimatedMonthlyBasePay"),
            "estimatedMonthlyOvertimePay": obj.get("estimatedMonthlyOvertimePay"),
            "estimatedMonthlyBonusPay": obj.get("estimatedMonthlyBonusPay"),
            "estimatedMonthlyOtherPay": obj.get("estimatedMonthlyOtherPay"),
            "estimatedMonthlyTotalPay": obj.get("estimatedMonthlyTotalPay"),
            "estimatedMonthlyCommissionPay": obj.get("estimatedMonthlyCommissionPay")
        })
        return _obj


