# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List
from openapi_client.models.obb_average_weekly_balance import ObbAverageWeeklyBalance
from typing import Optional, Set
from typing_extensions import Self

class ObbNumWeeksAverageBalanceIncreasing(BaseModel):
    """
    Report of average account balance week over week and count of weeks where the average balance increased
    """ # noqa: E501
    historic_average_weekly_balances: List[ObbAverageWeeklyBalance] = Field(description="Average weekly balances over the known history", alias="historicAverageWeeklyBalances")
    historic_number_of_weeks_average_balance_increasing: StrictInt = Field(description="Number of weeks during the known history where the average balance of the account increased week over week", alias="historicNumberOfWeeksAverageBalanceIncreasing")
    historic_number_of_weeks_with_data_available: StrictInt = Field(description="Number of weeks during the history in which data was available", alias="historicNumberOfWeeksWithDataAvailable")
    __properties: ClassVar[List[str]] = ["historicAverageWeeklyBalances", "historicNumberOfWeeksAverageBalanceIncreasing", "historicNumberOfWeeksWithDataAvailable"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ObbNumWeeksAverageBalanceIncreasing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in historic_average_weekly_balances (list)
        _items = []
        if self.historic_average_weekly_balances:
            for _item_historic_average_weekly_balances in self.historic_average_weekly_balances:
                if _item_historic_average_weekly_balances:
                    _items.append(_item_historic_average_weekly_balances.to_dict())
            _dict['historicAverageWeeklyBalances'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ObbNumWeeksAverageBalanceIncreasing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "historicAverageWeeklyBalances": [ObbAverageWeeklyBalance.from_dict(_item) for _item in obj["historicAverageWeeklyBalances"]] if obj.get("historicAverageWeeklyBalances") is not None else None,
            "historicNumberOfWeeksAverageBalanceIncreasing": obj.get("historicNumberOfWeeksAverageBalanceIncreasing"),
            "historicNumberOfWeeksWithDataAvailable": obj.get("historicNumberOfWeeksWithDataAvailable")
        })
        return _obj


