# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from openapi_client.models.state_time_interval import StateTimeInterval
from typing import Optional, Set
from typing_extensions import Self

class StateAttribute(BaseModel):
    """
    An attribute which represents some state over time, such as a balance or a calculation, including derivatives, ratios, or projections. Reports the state over the requested time interval(s).
    """ # noqa: E501
    attribute_name: StrictStr = Field(description="Name of Attribute as mentioned in Data Dictionary", alias="attributeName")
    reported_by_time_periods: List[StateTimeInterval] = Field(description="List of state values grouped by specified Time Interval", alias="reportedByTimePeriods")
    __properties: ClassVar[List[str]] = ["attributeName", "reportedByTimePeriods"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StateAttribute from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in reported_by_time_periods (list)
        _items = []
        if self.reported_by_time_periods:
            for _item_reported_by_time_periods in self.reported_by_time_periods:
                if _item_reported_by_time_periods:
                    _items.append(_item_reported_by_time_periods.to_dict())
            _dict['reportedByTimePeriods'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StateAttribute from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attributeName": obj.get("attributeName"),
            "reportedByTimePeriods": [StateTimeInterval.from_dict(_item) for _item in obj["reportedByTimePeriods"]] if obj.get("reportedByTimePeriods") is not None else None
        })
        return _obj


