# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.event import Event
from typing import Optional, Set
from typing_extensions import Self

class SubscriptionDetail(BaseModel):
    """
    SubscriptionDetail
    """ # noqa: E501
    subscription_id: Annotated[str, Field(min_length=36, strict=True, max_length=36)] = Field(description="A unique UUID identifier for the subscription.", alias="subscriptionId")
    url: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=2048)]] = Field(default=None, description="The webhook Url where the event notifications will be sent. The URL must be aligned with RFC 2396.")
    events: List[Event] = Field(description="List of events for the subscription.")
    status: Annotated[str, Field(min_length=1, strict=True, max_length=10)] = Field(description="The status of the event (e.g. active, inactive, pending, removed).")
    created_date: datetime = Field(description="Subcription creation date.", alias="createdDate")
    last_updated_date: datetime = Field(description="Subcription last updated date.", alias="lastUpdatedDate")
    __properties: ClassVar[List[str]] = ["subscriptionId", "url", "events", "status", "createdDate", "lastUpdatedDate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubscriptionDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in events (list)
        _items = []
        if self.events:
            for _item_events in self.events:
                if _item_events:
                    _items.append(_item_events.to_dict())
            _dict['events'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubscriptionDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "subscriptionId": obj.get("subscriptionId"),
            "url": obj.get("url"),
            "events": [Event.from_dict(_item) for _item in obj["events"]] if obj.get("events") is not None else None,
            "status": obj.get("status"),
            "createdDate": obj.get("createdDate"),
            "lastUpdatedDate": obj.get("lastUpdatedDate")
        })
        return _obj


