# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.payment_enablement_bundle_api import PaymentEnablementBundleApi


class TestPaymentEnablementBundleApi(unittest.TestCase):
    """PaymentEnablementBundleApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PaymentEnablementBundleApi()

    def tearDown(self) -> None:
        pass

    def test_get_account_details_by_account_id(self) -> None:
        """Test case for get_account_details_by_account_id

        Fetch all the requested details using the account ID
        """
        pass

    def test_get_account_details_by_institution_login_id(self) -> None:
        """Test case for get_account_details_by_institution_login_id

        Fetch all the requested field details using institution login ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
