# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.obb_num_weeks_average_balance_increasing import ObbNumWeeksAverageBalanceIncreasing

class TestObbNumWeeksAverageBalanceIncreasing(unittest.TestCase):
    """ObbNumWeeksAverageBalanceIncreasing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ObbNumWeeksAverageBalanceIncreasing:
        """Test ObbNumWeeksAverageBalanceIncreasing
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ObbNumWeeksAverageBalanceIncreasing`
        """
        model = ObbNumWeeksAverageBalanceIncreasing()
        if include_optional:
            return ObbNumWeeksAverageBalanceIncreasing(
                historic_average_weekly_balances = [
                    openapi_client.models.obb_average_weekly_balance.ObbAverageWeeklyBalance(
                        amount = 679.07, 
                        from_date = '2020-01-01', 
                        to_date = '2020-01-07', 
                        week = 1, )
                    ],
                historic_number_of_weeks_average_balance_increasing = 3,
                historic_number_of_weeks_with_data_available = 4
            )
        else:
            return ObbNumWeeksAverageBalanceIncreasing(
                historic_average_weekly_balances = [
                    openapi_client.models.obb_average_weekly_balance.ObbAverageWeeklyBalance(
                        amount = 679.07, 
                        from_date = '2020-01-01', 
                        to_date = '2020-01-07', 
                        week = 1, )
                    ],
                historic_number_of_weeks_average_balance_increasing = 3,
                historic_number_of_weeks_with_data_available = 4,
        )
        """

    def testObbNumWeeksAverageBalanceIncreasing(self):
        """Test ObbNumWeeksAverageBalanceIncreasing"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
