# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_institutions_institution_id_login_forms_request import PostInstitutionsInstitutionIdLoginFormsRequest

class TestPostInstitutionsInstitutionIdLoginFormsRequest(unittest.TestCase):
    """PostInstitutionsInstitutionIdLoginFormsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostInstitutionsInstitutionIdLoginFormsRequest:
        """Test PostInstitutionsInstitutionIdLoginFormsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostInstitutionsInstitutionIdLoginFormsRequest`
        """
        model = PostInstitutionsInstitutionIdLoginFormsRequest()
        if include_optional:
            return PostInstitutionsInstitutionIdLoginFormsRequest(
                language = 'en',
                customer_id = '1005061234',
                configuration_id = '605543e1-f507-48ad-8127-95c40566597b',
                service_agreement = openapi_client.models.service_agreement.ServiceAgreement(
                    language = 'en', 
                    accepted_date = '2024-11-28T18:25:32Z', )
            )
        else:
            return PostInstitutionsInstitutionIdLoginFormsRequest(
                language = 'en',
                customer_id = '1005061234',
                service_agreement = openapi_client.models.service_agreement.ServiceAgreement(
                    language = 'en', 
                    accepted_date = '2024-11-28T18:25:32Z', ),
        )
        """

    def testPostInstitutionsInstitutionIdLoginFormsRequest(self):
        """Test PostInstitutionsInstitutionIdLoginFormsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
