# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.branding import Branding

class TestBranding(unittest.TestCase):
    """Branding unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Branding:
        """Test Branding
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Branding`
        """
        model = Branding()
        if include_optional:
            return Branding(
                logo = 'https://prod-carpintero-branding.s3.us-west-2.amazonaws.com/5/logo.svg',
                alternate_logo = 'https://prod-carpintero-branding.s3.us-west-2.amazonaws.com/5/alternateLogo.svg',
                icon = 'https://prod-carpintero-branding.s3.us-west-2.amazonaws.com/5/icon.svg',
                primary_color = '#0167AE',
                tile = 'https://prod-carpintero-branding.s3.us-west-2.amazonaws.com/5/tile.svg'
            )
        else:
            return Branding(
        )
        """

    def testBranding(self):
        """Test Branding"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
