# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.consumer_info import ConsumerInfo

class TestConsumerInfo(unittest.TestCase):
    """ConsumerInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConsumerInfo:
        """Test ConsumerInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConsumerInfo`
        """
        model = ConsumerInfo()
        if include_optional:
            return ConsumerInfo(
                ssn = '999999999',
                dob = 1607450357
            )
        else:
            return ConsumerInfo(
                ssn = '999999999',
        )
        """

    def testConsumerInfo(self):
        """Test ConsumerInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
