# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.prequalification_report_constraints_out import PrequalificationReportConstraintsOut

class TestPrequalificationReportConstraintsOut(unittest.TestCase):
    """PrequalificationReportConstraintsOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PrequalificationReportConstraintsOut:
        """Test PrequalificationReportConstraintsOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrequalificationReportConstraintsOut`
        """
        model = PrequalificationReportConstraintsOut()
        if include_optional:
            return PrequalificationReportConstraintsOut(
                account_ids = ["5011648377","5011648378","5011648379"],
                report_custom_fields = [
                    openapi_client.models.report_custom_field.ReportCustomField(
                        label = 'loanID', 
                        value = '123456', 
                        shown = True, )
                    ],
                show_nsf = False,
                from_date = 1607450357
            )
        else:
            return PrequalificationReportConstraintsOut(
        )
        """

    def testPrequalificationReportConstraintsOut(self):
        """Test PrequalificationReportConstraintsOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
