# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.businesses_api_api import BusinessesAPIApi


class TestBusinessesAPIApi(unittest.TestCase):
    """BusinessesAPIApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BusinessesAPIApi()

    def tearDown(self) -> None:
        pass

    def test_add_business_details(self) -> None:
        """Test case for add_business_details

        Create a New Business for a Customer
        """
        pass

    def test_get_business_by_customer(self) -> None:
        """Test case for get_business_by_customer

        Get Business for Customer
        """
        pass

    def test_get_business_by_id(self) -> None:
        """Test case for get_business_by_id

        Get Business by ID
        """
        pass

    def test_update_business(self) -> None:
        """Test case for update_business

        Update Business by ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
