# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.cash_flow_cash_flow_debit import CashFlowCashFlowDebit

class TestCashFlowCashFlowDebit(unittest.TestCase):
    """CashFlowCashFlowDebit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CashFlowCashFlowDebit:
        """Test CashFlowCashFlowDebit
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CashFlowCashFlowDebit`
        """
        model = CashFlowCashFlowDebit()
        if include_optional:
            return CashFlowCashFlowDebit(
                monthly_cash_flow_debits = [
                    openapi_client.models.cash_flow_monthlycashflow_debits.CashFlowMonthlycashflowDebits(
                        month = 1512111600, 
                        number_of_debits = '5', 
                        total_debits_amount = -12345, 
                        largest_debit = -2000, 
                        number_of_debits_less_transfers = '3', 
                        total_debits_amount_less_transfers = -2000, 
                        average_debit_amount = 500, )
                    ],
                twelve_month_debit_total = 1200,
                twelve_month_debit_total_less_transfers = 1000,
                six_month_debit_total = 750,
                six_month_debit_total_less_transfers = 500,
                two_month_debit_total = 150,
                two_month_debit_total_less_transfers = 100
            )
        else:
            return CashFlowCashFlowDebit(
                monthly_cash_flow_debits = [
                    openapi_client.models.cash_flow_monthlycashflow_debits.CashFlowMonthlycashflowDebits(
                        month = 1512111600, 
                        number_of_debits = '5', 
                        total_debits_amount = -12345, 
                        largest_debit = -2000, 
                        number_of_debits_less_transfers = '3', 
                        total_debits_amount_less_transfers = -2000, 
                        average_debit_amount = 500, )
                    ],
        )
        """

    def testCashFlowCashFlowDebit(self):
        """Test CashFlowCashFlowDebit"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
