# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.voie_with_interview_data import VOIEWithInterviewData

class TestVOIEWithInterviewData(unittest.TestCase):
    """VOIEWithInterviewData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VOIEWithInterviewData:
        """Test VOIEWithInterviewData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VOIEWithInterviewData`
        """
        model = VOIEWithInterviewData()
        if include_optional:
            return VOIEWithInterviewData(
                tx_verify_interview = [
                    openapi_client.models.tx_verify_interview.TxVerifyInterview(
                        asset_id = '097545c5-1c2a-4f20-a5ef-77f0820344c9-2018601178', 
                        accounts = ["5011648377","5011648378","5011648379"], )
                    ],
                extract_earnings = True,
                extract_deductions = True,
                extract_direct_deposit = True
            )
        else:
            return VOIEWithInterviewData(
                tx_verify_interview = [
                    openapi_client.models.tx_verify_interview.TxVerifyInterview(
                        asset_id = '097545c5-1c2a-4f20-a5ef-77f0820344c9-2018601178', 
                        accounts = ["5011648377","5011648378","5011648379"], )
                    ],
        )
        """

    def testVOIEWithInterviewData(self):
        """Test VOIEWithInterviewData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
