# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.verify_assets_api import VerifyAssetsApi


class TestVerifyAssetsApi(unittest.TestCase):
    """VerifyAssetsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VerifyAssetsApi()

    def tearDown(self) -> None:
        pass

    def test_generate_prequalification_cra_report(self) -> None:
        """Test case for generate_prequalification_cra_report

        Generate PreQualification (CRA) Report for the customer
        """
        pass

    def test_generate_prequalification_non_cra_report(self) -> None:
        """Test case for generate_prequalification_non_cra_report

        Generate Prequalification (Non-CRA) Report
        """
        pass

    def test_generate_voa_report(self) -> None:
        """Test case for generate_voa_report

        Generate VOA Report for the customer
        """
        pass

    def test_generate_voa_with_income_report(self) -> None:
        """Test case for generate_voa_with_income_report

        Generate VOA With Income Report for the customer
        """
        pass


if __name__ == '__main__':
    unittest.main()
