# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.financial_institution import FinancialInstitution

class TestFinancialInstitution(unittest.TestCase):
    """FinancialInstitution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FinancialInstitution:
        """Test FinancialInstitution
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FinancialInstitution`
        """
        model = FinancialInstitution()
        if include_optional:
            return FinancialInstitution(
                institution_id = 102224,
                institution_name = 'Chase',
                status = True,
                created_date = '2020-07-30T16:11:23Z',
                modified_date = '2020-07-30T16:11:23Z'
            )
        else:
            return FinancialInstitution(
        )
        """

    def testFinancialInstitution(self):
        """Test FinancialInstitution"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
