# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.report_transaction import ReportTransaction

class TestReportTransaction(unittest.TestCase):
    """ReportTransaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReportTransaction:
        """Test ReportTransaction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReportTransaction`
        """
        model = ReportTransaction()
        if include_optional:
            return ReportTransaction(
                id = 21284820852,
                amount = 100,
                posted_date = 1571313600,
                description = 'ATM CHECK DEPOSIT mm/dd',
                memo = 'Some St Somewhere City State',
                normalized_payee = 'T-Mobile',
                institution_transaction_id = '0000000000',
                category = 'Income',
                type = 'debit',
                security_type = 'Stock',
                symbol = 'DAL',
                commission = 0
            )
        else:
            return ReportTransaction(
                id = 21284820852,
                posted_date = 1571313600,
                description = 'ATM CHECK DEPOSIT mm/dd',
        )
        """

    def testReportTransaction(self):
        """Test ReportTransaction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
