# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.transaction_data_enrichment_api import TransactionDataEnrichmentApi


class TestTransactionDataEnrichmentApi(unittest.TestCase):
    """TransactionDataEnrichmentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionDataEnrichmentApi()

    def tearDown(self) -> None:
        pass

    def test_enrich_transactions(self) -> None:
        """Test case for enrich_transactions

        Performs enrichment of the provided transactions
        """
        pass


if __name__ == '__main__':
    unittest.main()
