# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pay_switches_summary_switches_inner import PaySwitchesSummarySwitchesInner

class TestPaySwitchesSummarySwitchesInner(unittest.TestCase):
    """PaySwitchesSummarySwitchesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaySwitchesSummarySwitchesInner:
        """Test PaySwitchesSummarySwitchesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaySwitchesSummarySwitchesInner`
        """
        model = PaySwitchesSummarySwitchesInner()
        if include_optional:
            return PaySwitchesSummarySwitchesInner(
                id = '602414d84f9a1980cf5eafcc',
                status = 'completed',
                failure_reason = 'connection-error',
                created_date = '2023-07-25T08:14:20Z'
            )
        else:
            return PaySwitchesSummarySwitchesInner(
                id = '602414d84f9a1980cf5eafcc',
                status = 'completed',
                created_date = '2023-07-25T08:14:20Z',
        )
        """

    def testPaySwitchesSummarySwitchesInner(self):
        """Test PaySwitchesSummarySwitchesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
