# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.earnings import Earnings

class TestEarnings(unittest.TestCase):
    """Earnings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Earnings:
        """Test Earnings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Earnings`
        """
        model = Earnings()
        if include_optional:
            return Earnings(
                name = 'bonusPayAmount',
                type = 'bonus',
                rate = 19,
                amount = 589,
                amount_ytd = 14301.25
            )
        else:
            return Earnings(
                type = 'bonus',
                amount = 589,
        )
        """

    def testEarnings(self):
        """Test Earnings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
