# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.paystub_monthly_income_record import PaystubMonthlyIncomeRecord

class TestPaystubMonthlyIncomeRecord(unittest.TestCase):
    """PaystubMonthlyIncomeRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaystubMonthlyIncomeRecord:
        """Test PaystubMonthlyIncomeRecord
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaystubMonthlyIncomeRecord`
        """
        model = PaystubMonthlyIncomeRecord()
        if include_optional:
            return PaystubMonthlyIncomeRecord(
                estimated_monthly_base_pay = 2000,
                estimated_monthly_overtime_pay = 50,
                estimated_monthly_bonus_pay = 20,
                estimated_monthly_commission_pay = 50
            )
        else:
            return PaystubMonthlyIncomeRecord(
        )
        """

    def testPaystubMonthlyIncomeRecord(self):
        """Test PaystubMonthlyIncomeRecord"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
