# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.prequalification_report_asset_summary import PrequalificationReportAssetSummary

class TestPrequalificationReportAssetSummary(unittest.TestCase):
    """PrequalificationReportAssetSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PrequalificationReportAssetSummary:
        """Test PrequalificationReportAssetSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrequalificationReportAssetSummary`
        """
        model = PrequalificationReportAssetSummary()
        if include_optional:
            return PrequalificationReportAssetSummary(
                type = 'checking',
                available_balance = 1000,
                current_balance = 1000,
                two_month_average = -1865.96,
                six_month_average = -7616.01,
                beginning_balance = -17795.6
            )
        else:
            return PrequalificationReportAssetSummary(
                current_balance = 1000,
                two_month_average = -1865.96,
                beginning_balance = -17795.6,
        )
        """

    def testPrequalificationReportAssetSummary(self):
        """Test PrequalificationReportAssetSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
