# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.third_party_access_api import ThirdPartyAccessApi


class TestThirdPartyAccessApi(unittest.TestCase):
    """ThirdPartyAccessApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ThirdPartyAccessApi()

    def tearDown(self) -> None:
        pass

    def test_generate_third_party_access_key(self) -> None:
        """Test case for generate_third_party_access_key

        Generate Third Party Access Key
        """
        pass

    def test_revoke_third_party_access_key(self) -> None:
        """Test case for revoke_third_party_access_key

        Revoke Third Party Access
        """
        pass

    def test_update_third_party_access_key(self) -> None:
        """Test case for update_third_party_access_key

        Update Third Party Access
        """
        pass


if __name__ == '__main__':
    unittest.main()
