# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.certified_institutions import CertifiedInstitutions

class TestCertifiedInstitutions(unittest.TestCase):
    """CertifiedInstitutions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CertifiedInstitutions:
        """Test CertifiedInstitutions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CertifiedInstitutions`
        """
        model = CertifiedInstitutions()
        if include_optional:
            return CertifiedInstitutions(
                found = 200,
                displaying = 1,
                more_available = True,
                requested_date = 1607450357,
                institutions = [
                    openapi_client.models.certified_institution.CertifiedInstitution(
                        id = 4222, 
                        rssd = 490535, 
                        name = 'FinBank', 
                        trans_agg = True, 
                        ach = True, 
                        state_agg = False, 
                        voi = True, 
                        voa = True, 
                        aha = False, 
                        avail_balance = False, 
                        account_owner = True, 
                        student_loan_data = True, 
                        loan_payment_details = True, 
                        child_institutions = [
                            openapi_client.models.child_institution.ChildInstitution(
                                rssd = 490535, 
                                parent_rssd = 490535, 
                                name = 'FinBank', 
                                institution_id = 4222, )
                            ], )
                    ]
            )
        else:
            return CertifiedInstitutions(
                found = 200,
                displaying = 1,
                more_available = True,
                requested_date = 1607450357,
                institutions = [
                    openapi_client.models.certified_institution.CertifiedInstitution(
                        id = 4222, 
                        rssd = 490535, 
                        name = 'FinBank', 
                        trans_agg = True, 
                        ach = True, 
                        state_agg = False, 
                        voi = True, 
                        voa = True, 
                        aha = False, 
                        avail_balance = False, 
                        account_owner = True, 
                        student_loan_data = True, 
                        loan_payment_details = True, 
                        child_institutions = [
                            openapi_client.models.child_institution.ChildInstitution(
                                rssd = 490535, 
                                parent_rssd = 490535, 
                                name = 'FinBank', 
                                institution_id = 4222, )
                            ], )
                    ],
        )
        """

    def testCertifiedInstitutions(self):
        """Test CertifiedInstitutions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
