# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.obb_data_availability import ObbDataAvailability

class TestObbDataAvailability(unittest.TestCase):
    """ObbDataAvailability unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ObbDataAvailability:
        """Test ObbDataAvailability
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ObbDataAvailability`
        """
        model = ObbDataAvailability()
        if include_optional:
            return ObbDataAvailability(
                historic_availability_begin_date = '2022-03-01',
                historic_availability_end_date = '2022-03-30',
                historic_available_days = 30,
                historic_data_availability = 'Data is available from 2022-03-01 to 2022-03-30'
            )
        else:
            return ObbDataAvailability(
                historic_available_days = 30,
                historic_data_availability = 'Data is available from 2022-03-01 to 2022-03-30',
        )
        """

    def testObbDataAvailability(self):
        """Test ObbDataAvailability"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
