# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.customer_account_multiple_statement import CustomerAccountMultipleStatement

class TestCustomerAccountMultipleStatement(unittest.TestCase):
    """CustomerAccountMultipleStatement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerAccountMultipleStatement:
        """Test CustomerAccountMultipleStatement
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerAccountMultipleStatement`
        """
        model = CustomerAccountMultipleStatement()
        if include_optional:
            return CustomerAccountMultipleStatement(
                id = '097545c5-1c2a-4f20-a5ef-77f0820344c9-2018601178',
                description = '',
                as_of_date = 1607450357,
                document_date = '',
                index = '',
                code = '',
                message = ''
            )
        else:
            return CustomerAccountMultipleStatement(
                as_of_date = 1607450357,
                index = '',
        )
        """

    def testCustomerAccountMultipleStatement(self):
        """Test CustomerAccountMultipleStatement"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
