# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.micro_entry_verify_request_parameter import MicroEntryVerifyRequestParameter

class TestMicroEntryVerifyRequestParameter(unittest.TestCase):
    """MicroEntryVerifyRequestParameter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MicroEntryVerifyRequestParameter:
        """Test MicroEntryVerifyRequestParameter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MicroEntryVerifyRequestParameter`
        """
        model = MicroEntryVerifyRequestParameter()
        if include_optional:
            return MicroEntryVerifyRequestParameter(
                partner_id = '1234583871234',
                customer_id = '1005061234',
                redirect_uri = 'https://www.finicity.com/connect/',
                webhook = 'https://webhook.site/8d4421a7-d1d1-4f01-bb08-5370aff0321b',
                webhook_content_type = 'application/json',
                webhook_data = None,
                webhook_headers = None,
                experience = 'default',
                account_id = '5011648377'
            )
        else:
            return MicroEntryVerifyRequestParameter(
        )
        """

    def testMicroEntryVerifyRequestParameter(self):
        """Test MicroEntryVerifyRequestParameter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
