# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.accounts_api import AccountsApi


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_customer_account(self) -> None:
        """Test case for delete_customer_account

        Delete Access to Customer Account by ID
        """
        pass

    def test_delete_customer_accounts_by_institution_login(self) -> None:
        """Test case for delete_customer_accounts_by_institution_login

        Delete Access to Customer Accounts by Institution Login ID
        """
        pass

    def test_get_customer_account(self) -> None:
        """Test case for get_customer_account

        Get Customer Account by ID
        """
        pass

    def test_get_customer_accounts(self) -> None:
        """Test case for get_customer_accounts

        Get Customer Accounts
        """
        pass

    def test_get_customer_accounts_by_institution(self) -> None:
        """Test case for get_customer_accounts_by_institution

        Get Customer Accounts by Institution ID
        """
        pass

    def test_get_customer_accounts_by_institution_login(self) -> None:
        """Test case for get_customer_accounts_by_institution_login

        Get Customer Accounts by Institution Login ID
        """
        pass

    def test_refresh_customer_accounts(self) -> None:
        """Test case for refresh_customer_accounts

        Refresh Customer Accounts
        """
        pass

    def test_refresh_customer_accounts_by_institution_login(self) -> None:
        """Test case for refresh_customer_accounts_by_institution_login

        Refresh Customer Accounts by Institution Login ID
        """
        pass

    def test_refresh_customer_accounts_by_institution_login_v2(self) -> None:
        """Test case for refresh_customer_accounts_by_institution_login_v2

        Refresh Customer Account by Institution Login ID for Data Access Tiers
        """
        pass

    def test_refresh_customer_accounts_v2(self) -> None:
        """Test case for refresh_customer_accounts_v2

        Refresh Customer Accounts for Data Access Tiers
        """
        pass


if __name__ == '__main__':
    unittest.main()
