# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.third_party_access_key_receipt_data import ThirdPartyAccessKeyReceiptData

class TestThirdPartyAccessKeyReceiptData(unittest.TestCase):
    """ThirdPartyAccessKeyReceiptData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ThirdPartyAccessKeyReceiptData:
        """Test ThirdPartyAccessKeyReceiptData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ThirdPartyAccessKeyReceiptData`
        """
        model = ThirdPartyAccessKeyReceiptData()
        if include_optional:
            return ThirdPartyAccessKeyReceiptData(
                data = [
                    openapi_client.models.third_party_access_receipt_data.ThirdPartyAccessReceiptData(
                        receipt = openapi_client.models.third_party_access_receipt.ThirdPartyAccessReceipt(
                            profile = 3, 
                            version = '1', 
                            receipt_id = 'cr_4pfI2r1X8aOHrDDwrwC01NHTxOXlT1', 
                            customer_id = '3465230025077724000', 
                            partner_id = '1234583871234', 
                            products = [
                                openapi_client.models.third_party_access_product.ThirdPartyAccessProduct(
                                    product = 'moneyTransferDetails', 
                                    payor_id = '2445581559892', 
                                    max_calls = 200, 
                                    account_id = '5011648377', 
                                    access_period = openapi_client.models.third_party_access_period.ThirdPartyAccessPeriod(
                                        type = 'timeframe', 
                                        start_time = '2022-03-10T06:06:20.042584549Z', 
                                        end_time = '2022-03-10T06:06:20.042584549Z', ), )
                                ], 
                            provenance = openapi_client.models.third_party_access_provenance.ThirdPartyAccessProvenance(
                                client_fingerprint = 'LU9ZYxcDNQCwEmAxH52XFzaRiGMAAAAABclSKxW5S9P8pUMDV4fbpg', 
                                ip_address = '8.8.8.8', 
                                token = 'P9YbR+srNVyQI35893d+BzPrhGMAAAAAuacVUt+3m4svbaFjVSbHEA==', ), 
                            timestamp = '2022-03-10T06:06:20.042584549Z', ), 
                        proof = openapi_client.models.third_party_access_proof.ThirdPartyAccessProof(
                            signature = 'JTdCyTIyY3VzdG9tZXJJZCUyMiUzQSUyMjU0NTQ1MTQwMDI5NTU2MjkzNDMlMjIlMkMlMjJwYXJ0bmVySWQlMjIlM0ElMjIyNDQ1NTgzOTIyNTM2JTIyJTJDJTIycHJvZHVjdHMlMjIlM0ElNUIlN0IlMjJhY2Nlc3NQZXJpb2QlMjIlM0ElN0IlMjJlbmRUaW1lJTIyJTNBJTIyMjAyMy0xMS0yOVQwNiUzQTA2JTNBMjBaJTIyJTJDJTIyc3RhcnRUaW1lJTIyJTNBJTIyMjAyMi0xMS0yOVQwNiUzQTA2JTNBMjBaJTIyJTJDJTIydHlwZSUyMiUzQSUyMnRpbWVmcmFtZSUyMiU3RCUyQyUyMmFjY291bnRJZCUyMiUzQSUyMjQ2MzM0MTU3NDM5NjAzNzQwMjQlMjIlMkMlMjJwcm9kdWN0JTIyJTNBJTIybW9uZXlUcmFuc2ZlckRldGFpbHMlMjIlN0QlMkMlN0IlMjJhY2Nlc3NQZXJpb2QlMjIlM0ElN0IlMjJlbmRUaW1lJTIyJTNBJTIyMjAyMy0xMC0yOVQwNiUzQTA2JTNBMjBaJTIyJTJDJTIyc3RhcnRUaW1lJTIyJTNBJTIyMjAyMi0xMS0yOVQwNiUzQTA2JTNBMjBaJTIyJTJDJTIydHlwZSUyMiUzQSUyMnRpbWVmcmFtZSUyMiU3RCUyQyUyMmFjY291bnRJZCUyMiUzQSUyMjQ2MzM0MTU3NDM5NjAzNzQwMjQlMjIlMkMlMjJwcm9kdWN0JTIyJTNBJTIybW9uZXlUcmFuc2ZlckRldGFpbHMlMjIlN0QlNUQlMkMlMjJwcm9maWxlJTIyJTNBMyUyQyUyMnByb3ZlbmFuY2UlMjIlM0FudWxsJTJDJTIycmVjZWlwdElkJTIyJTNBJTIyY3JfNHBmSTNyMVg4YU9IckREd3J3QzAxTkhDeE9YbFcxJTIyJTJDJTIycmVjZWlwdFZlcnNpb24lMjIlM0ExJTJDJTIydGltZXN0YW1wJTIyJTNBJTIyMjAyMi0xMS0yOVQxOCUzQTM1JTNBMDhaJTIyJTJDJTIydmVyc2lvbiUyMiUzQSUyMjElRjYlN9U=', 
                            key_id = '867-530-900', ), )
                    ]
            )
        else:
            return ThirdPartyAccessKeyReceiptData(
        )
        """

    def testThirdPartyAccessKeyReceiptData(self):
        """Test ThirdPartyAccessKeyReceiptData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
