# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.connect_transfer_deposit_switch_link import ConnectTransferDepositSwitchLink

class TestConnectTransferDepositSwitchLink(unittest.TestCase):
    """ConnectTransferDepositSwitchLink unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConnectTransferDepositSwitchLink:
        """Test ConnectTransferDepositSwitchLink
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConnectTransferDepositSwitchLink`
        """
        model = ConnectTransferDepositSwitchLink()
        if include_optional:
            return ConnectTransferDepositSwitchLink(
                link = 'https://connect2.finicity.com?customerId=6007761187&origin=url&partnerId=2445582695152&signature=f4d278f9d0b4a54f6bc2e71aa00607900365a2625bdb5bc9ca0eaec1c4158de8&timestamp=1660164260516&ttl=1660171460516type=transferDepositSwitch'
            )
        else:
            return ConnectTransferDepositSwitchLink(
        )
        """

    def testConnectTransferDepositSwitchLink(self):
        """Test ConnectTransferDepositSwitchLink"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
