# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.obb_error_message import ObbErrorMessage

class TestObbErrorMessage(unittest.TestCase):
    """ObbErrorMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ObbErrorMessage:
        """Test ObbErrorMessage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ObbErrorMessage`
        """
        model = ObbErrorMessage()
        if include_optional:
            return ObbErrorMessage(
                error_code = 404,
                message = 'Customer Id does not exist'
            )
        else:
            return ObbErrorMessage(
                error_code = 404,
                message = 'Customer Id does not exist',
        )
        """

    def testObbErrorMessage(self):
        """Test ObbErrorMessage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
