# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.prequalification_report_account import PrequalificationReportAccount

class TestPrequalificationReportAccount(unittest.TestCase):
    """PrequalificationReportAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PrequalificationReportAccount:
        """Test PrequalificationReportAccount
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrequalificationReportAccount`
        """
        model = PrequalificationReportAccount()
        if include_optional:
            return PrequalificationReportAccount(
                id = 1000023996,
                number = '1111',
                owner_name = 'PATRICK PURCHASER|LORRAINE PURCHASER',
                owner_address = '7195 BELMONT ST. PARLIN, NJ 08859',
                owner_as_of_date = 1596175200,
                name = 'Checking',
                type = 'checking',
                currency = 'USD',
                aggregation_status_code = 0,
                balance = 501.24,
                balance_date = 1588350276,
                available_balance = 1000,
                average_monthly_balance = 501.02,
                tot_number_insufficient_funds_fee_debit_tx_account = 0,
                tot_number_insufficient_funds_fee_debit_tx_over6_months_account = 0,
                tot_number_days_since_most_recent_insufficient_funds_fee_debit_tx_account = 120,
                transactions = [
                    openapi_client.models.report_transaction.ReportTransaction()
                    ],
                asset = openapi_client.models.prequalification_report_asset_summary.PrequalificationReportAssetSummary(
                    type = 'checking', 
                    available_balance = 1000, 
                    current_balance = 1000, 
                    two_month_average = -1865.96, 
                    six_month_average = -7616.01, 
                    beginning_balance = -17795.6, ),
                details = openapi_client.models.account_details.AccountDetails(
                    interest_margin_balance = -50000, 
                    available_cash_balance = 1500, 
                    vested_balance = 300000, 
                    current_loan_balance = 0, 
                    available_balance_amount = 1000, )
            )
        else:
            return PrequalificationReportAccount(
        )
        """

    def testPrequalificationReportAccount(self):
        """Test PrequalificationReportAccount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
