# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.connect_generate_transfer_bill_pay_switch_parameters import ConnectGenerateTransferBillPaySwitchParameters

class TestConnectGenerateTransferBillPaySwitchParameters(unittest.TestCase):
    """ConnectGenerateTransferBillPaySwitchParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConnectGenerateTransferBillPaySwitchParameters:
        """Test ConnectGenerateTransferBillPaySwitchParameters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConnectGenerateTransferBillPaySwitchParameters`
        """
        model = ConnectGenerateTransferBillPaySwitchParameters()
        if include_optional:
            return ConnectGenerateTransferBillPaySwitchParameters(
                service_agreement = openapi_client.models.service_agreement.ServiceAgreement(
                    language = 'en', 
                    accepted_date = '2024-11-28T18:25:32Z', ),
                accounts = [{"accountNumber":"7526894126","bankIdentifier":"110000000","title":"My savings account","type":"savings"},{"accountNumber":"3740238560","bankIdentifier":"110000000","title":"Checking account 8560","type":"checking"}],
                partner_id = '1234583871234',
                customer_id = '1005061234',
                experience = '03099618-8a28-41f6-b891-83af336626d6',
                language = 'es',
                single_use_url = True,
                redirect_uri = 'https://www.finicity.com/connect/',
                cards = [
                    openapi_client.models.card.Card(
                        title = 'Mastercard super card', 
                        number = '4242424242424242', 
                        expiry = '12/27', 
                        cvv = '123', 
                        brand = 'Mastercard', )
                    ],
                identity = openapi_client.models.bill_pay_switch_identity.BillPaySwitchIdentity(
                    first_name = 'Jane', 
                    last_name = 'Doe', 
                    zip_code = '12345', 
                    address = '123 Lane', 
                    address2 = 'Apt 987', 
                    city = 'Purchase', 
                    state = 'NY', 
                    phone = '2121234567', 
                    email = 'jane.doe@example.com', )
            )
        else:
            return ConnectGenerateTransferBillPaySwitchParameters(
                partner_id = '1234583871234',
                customer_id = '1005061234',
                single_use_url = True,
                cards = [
                    openapi_client.models.card.Card(
                        title = 'Mastercard super card', 
                        number = '4242424242424242', 
                        expiry = '12/27', 
                        cvv = '123', 
                        brand = 'Mastercard', )
                    ],
                identity = openapi_client.models.bill_pay_switch_identity.BillPaySwitchIdentity(
                    first_name = 'Jane', 
                    last_name = 'Doe', 
                    zip_code = '12345', 
                    address = '123 Lane', 
                    address2 = 'Apt 987', 
                    city = 'Purchase', 
                    state = 'NY', 
                    phone = '2121234567', 
                    email = 'jane.doe@example.com', ),
        )
        """

    def testConnectGenerateTransferBillPaySwitchParameters(self):
        """Test ConnectGenerateTransferBillPaySwitchParameters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
