# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.application_response import ApplicationResponse

class TestApplicationResponse(unittest.TestCase):
    """ApplicationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApplicationResponse:
        """Test ApplicationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApplicationResponse`
        """
        model = ApplicationResponse()
        if include_optional:
            return ApplicationResponse(
                found = 200,
                displaying = 1,
                more_available = True,
                applications = [
                    openapi_client.models.app.App(
                        pre_app_id = 13, 
                        application_id = '234dsfdsf-535fdgdtrtr-546464564', 
                        status = 'A', 
                        name = 'Mvelopes', 
                        scopes = 'Account Number, Account Info', 
                        note = 'Approved', 
                        created_date = '2020-06-02T06:00:00Z', 
                        modified_date = '2020-06-02T06:00:00Z', 
                        submitted_date = '2020-06-02T06:00:00Z', )
                    ]
            )
        else:
            return ApplicationResponse(
        )
        """

    def testApplicationResponse(self):
        """Test ApplicationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
