# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.transactions_report_account import TransactionsReportAccount

class TestTransactionsReportAccount(unittest.TestCase):
    """TransactionsReportAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionsReportAccount:
        """Test TransactionsReportAccount
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionsReportAccount`
        """
        model = TransactionsReportAccount()
        if include_optional:
            return TransactionsReportAccount(
                id = 1000075473,
                name = 'Super Checking',
                number = '5015',
                type = 'checking',
                currency = 'USD',
                aggregation_status_code = 0,
                balance = 100000,
                balance_date = 1594676289,
                oldest_transaction_date = 1588350276,
                transactions_count = 3,
                transactions = [
                    openapi_client.models.report_transaction.ReportTransaction()
                    ]
            )
        else:
            return TransactionsReportAccount(
        )
        """

    def testTransactionsReportAccount(self):
        """Test TransactionsReportAccount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
