# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.report_income_estimate import ReportIncomeEstimate

class TestReportIncomeEstimate(unittest.TestCase):
    """ReportIncomeEstimate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReportIncomeEstimate:
        """Test ReportIncomeEstimate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReportIncomeEstimate`
        """
        model = ReportIncomeEstimate()
        if include_optional:
            return ReportIncomeEstimate(
                net_annual = 1000.12,
                projected_net_annual = 1500.23,
                estimated_gross_annual = 2000.12,
                projected_gross_annual = 2500.23
            )
        else:
            return ReportIncomeEstimate(
                net_annual = 1000.12,
                projected_net_annual = 1500.23,
                estimated_gross_annual = 2000.12,
                projected_gross_annual = 2500.23,
        )
        """

    def testReportIncomeEstimate(self):
        """Test ReportIncomeEstimate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
