# coding: utf-8

"""
    Open Finance

    OpenAPI specification for Finicity APIs.  Open Finance (formerly Open Banking) solutions in the US are provided by Finicity, a Mastercard company.

    The version of the OpenAPI document: 1.31.2
    Contact: apisupport@mastercard.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.app_registration_api import AppRegistrationApi


class TestAppRegistrationApi(unittest.TestCase):
    """AppRegistrationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AppRegistrationApi()

    def tearDown(self) -> None:
        pass

    def test_get_app_registration_status(self) -> None:
        """Test case for get_app_registration_status

        Get App Registration Status
        """
        pass

    def test_get_applications(self) -> None:
        """Test case for get_applications

        Get App Details
        """
        pass

    def test_get_registered_institutions(self) -> None:
        """Test case for get_registered_institutions

        Get App Registration Status by Institution
        """
        pass

    def test_migrate_institution_login_accounts(self) -> None:
        """Test case for migrate_institution_login_accounts

        Migrate Institution Login Accounts
        """
        pass

    def test_modify_app_registration(self) -> None:
        """Test case for modify_app_registration

        Modify App Registration
        """
        pass

    def test_register_app(self) -> None:
        """Test case for register_app

        Register App
        """
        pass

    def test_set_customer_app_id(self) -> None:
        """Test case for set_customer_app_id

        Set Customer App ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
